name: Track Goal Progress

on:
  schedule:
    - cron: "0 */5 * * *" # Every 5 hours
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  scrape:
    if: github.event_name != 'issues' || github.event.issue.title == 'update'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install playwright

      - name: Run scraper
        id: scrape
        run: node scrape.js

      - name: Commit goal progress
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add goal_progress.json
          git commit -m "Update goal progress"
          git push

      - name: Send to Discord
        uses: discordactions/send-to-discord@v1
        with:
          message: |
            📊 **Current Status:**
            - **Site Percentage:** ${{ steps.scrape.outputs.percentage }}%
            - **Balance:** ${{ steps.scrape.outputs.balance }}
            - **Goal Progress:** ${{ steps.scrape.outputs.percentage }}%
            - **Time Remaining:** ${{ steps.scrape.outputs.time_remaining }}

            🛒 **Affordable Items:**
            ${{ steps.scrape.outputs.formatted_items }}
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
